### PR TITLE
Heroku deploy

### PR DESCRIPTION
**Pull request by jpowell**

### CODE REVIEW

**Comment by jpowell** [comment]
Remaining to-dos
- [ ] Fix capybara-webkit dependency
- [ ] Fix specs in general
- [ ] CI
- [ ] disable old app running on prem

**Comment by gburgett** [comment]
Neato!  Looks good so far

**Comment by gburgett** [comment]
@jpowell is this the branch currently powering worship.watermark.org?

**Comment by gburgett** [comment]
@jpowell fixed CI!  I was hoping to try it in heroku

**Comment by jpowell** [comment]
Did you try this branch on Heroku?

**Pull request merged**
